export const states = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttarakhand",
  "Uttar Pradesh",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli",
  "Daman and Diu",
  "Delhi",
  "Lakshadweep",
  "Puducherry",
];

export const majorCities = [
  "Kolkata",
  "Howrah",
  "Durgapur",
  "Asansol",
  "Siliguri",
  "Bardhaman",
  "Malda",
  "Baharampur",
  "Haldia",
  "Kharagpur",
  "Jalpaiguri",
  "Shantipur",
  "Ranaghat",
  "Raiganj",
  "Krishnanagar",
  "Nabadwip",
  "Medinipur",
  "Purulia",
  "Bankura",
  "Cooch Behar",
  "Darjeeling",
  "Alipurduar",
  "Balurghat",
  "Basirhat",
  "Bongaon",
  "Barasat",
  "Diamond Harbour",
  "Bolpur",
  "Kalyani",
  "Chakdaha",
  "Kanchrapara",
  "Joynagar Majilpur",
  "Raipur",
  "Bhadreswar",
  "Naihati",
  "Serampore",
  "Rishra",
  "Habra",
  "Madhyamgram",
  "Baranagar",
  "Nadia",
  "North 24 Parganas",
  "South 24 Parganas",
  "Hooghly",
  "Murshidabad",
  "Purba Bardhaman",
  "Paschim Bardhaman",
  "Jhargram",
  "Kalimpong",
  "Arambagh",
  "Chinsurah",
  "Dum Dum",
  "Bally",
];
